//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <x86intrin.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------
int64_t f1(u_int64_t a1);
int64_t f2(int64_t a1, int64_t a2);
int64_t f3(int64_t a1, int64_t a2);
int64_t f4(int64_t a1, int64_t a2);
int64_t f5(int64_t a1, int64_t a2);
int64_t f6(int64_t a1);
int64_t segf(void);
// --------------------- Global Variables ---------------------
int32_t g1;
// ------------------------ Functions -------------------------
// Address range: 0x4006a6 - 0x4006b8
int64_t f1(u_int64_t a1) {
    // 0x4006a6
    return a1 % 64 ^ 59;
}
// Address range: 0x4006b8 - 0x400700
int64_t f2(int64_t a1, int64_t a2) {
	printf("%d|%d\n", a1, a2);
    // 0x4006b8
    if ((int32_t)a2 <= 0) {
        // 0x4006f5
        return 15;
    }
    int64_t v1 = 0;
    int32_t v2 = 0; // 0x4006e6
    v2 += (int32_t)*(char *)(v1 + a1);
    v1++;
    while (v1 != (a2 & 0xffffffff)) {
        // 0x4006d3
        v2 += (int32_t)*(char *)(v1 + a1);
        v1++;
    }
    // 0x4006f5
    return v2 % 64 ^ 15;
}
// Address range: 0x400700 - 0x40074e
int64_t f3(int64_t a1, int64_t a2) {
    // 0x400700
    if ((int32_t)a2 <= 0) {
        // 0x400743
        return 20;
    }
    int64_t v1 = 0;
    int32_t v2 = 1; // 0x400731
    v2 *= (int32_t)*(char *)(v1 + a1);
    v1++;
    while (v1 != (a2 & 0xffffffff)) {
        // 0x40071b
        v2 *= (int32_t)*(char *)(v1 + a1);
        v1++;
    }
    // 0x400743
    return v2 % 64 ^ 21;
}
// Address range: 0x40074e - 0x4007c4
int64_t f4(int64_t a1, int64_t a2) {
    // 0x40074e
    int64_t v1; // 0x40074e
    int32_t v2 = 0x1000000 * (int32_t)v1 / 0x1000000; // 0x400767
    if ((int32_t)a2 <= 0) {
        // 0x4007ad
        srand(v2 ^ 14);
        return rand() % 64;
    }
    int64_t v3 = 0;
    int32_t v4 = v2;
    int32_t v5 = (int32_t)*(char *)(v3 + a1); // 0x400789
    int32_t v6 = v4 < v5 ? v5 : v4;
    v3++;
    int32_t v7 = v6; // 0x4007ab
    while (v3 != (a2 & 0xffffffff)) {
        // 0x400773
        v4 = v6;
        v5 = (int32_t)*(char *)(v3 + a1);
        v6 = v4 < v5 ? v5 : v4;
        v3++;
        v7 = v6;
    }
    // 0x4007ad
    srand(v7 ^ 14);
    return rand() % 64;
}
// Address range: 0x4007c4 - 0x400821
int64_t f5(int64_t a1, int64_t a2) {
    // 0x4007c4
    if ((int32_t)a2 <= 0) {
        // 0x400817
        return 47;
    }
    int64_t v1 = 0;
    int32_t v2 = 0; // 0x400808
    int32_t v3 = (int32_t)*(char *)(v1 + a1); // 0x400805
    v2 += v3 * v3;
    v1++;
    while (v1 != (a2 & 0xffffffff)) {
        // 0x4007df
        v3 = (int32_t)*(char *)(v1 + a1);
        v2 += v3 * v3;
        v1++;
    }
    // 0x400817
    return v2 % 64 ^ 47;
}
// Address range: 0x400821 - 0x40085d
int64_t f6(int64_t a1) {
    // 0x400821
    u_int32_t v1; // 0x40083e
    for (int32_t i = 0; i < 0x1000000 * (int32_t)a1 / 0x1000000; i++) {
        // 0x40083e
        v1 = rand();
    }
    // 0x400853
    return v1 % 64 ^ 37;
}
// Address range: 0x40085d - 0x400881
int64_t segf(void) {
    // 0x40085d
    abort();
    // UNREACHABLE
}
// Address range: 0x400881 - 0x400aa2
int main(int argc, char ** argv) {
	int64_t v1;
    if ((int32_t)argc != 3) {
        // 0x400919
        segf();
        // UNREACHABLE
    }
    int64_t v2 = (int64_t)argv; // 0x40091e
    int64_t v3 = *(int64_t *)(v2 + 8); // 0x400922
    int64_t v4 = *(int64_t *)(v2 + 16); // 0x40092e
    char * str = (char *)v4; // 0x400932
	printf ("A|%p|%p\n", argv[2], v4);
	printf("f1%p|f2%p|f3%p|f4%p\n", f1, f2, f3, f4);
	printf("str: %p| argv[0]: %p|argv[1]: %p|argv[2]: %p\n", str, argv[0], argv[1], argv[2]);
    if (strlen(str) != 6) {
        // 0x400948
        segf();
        // UNREACHABLE
    }
    char * str2 = (char *)v3; // 0x400926
    int64_t len = strlen(str2); // 0x40095f
    int64_t v5 = f1(len); // 0x400961
    int64_t v6; // bp-8, 0x400881
    int64_t v7 = (int64_t)&v6 - 80; // 0x400975
	f1(len);
	printf ("A|%ld|%ld|%p\n", v5, v7, (char *)(0x100000000 * v5 / 0x100000000 + v7));
	printf("v5 + v7 :%p|| obfuscated one: %p\n", v5 + v7, (char *)(0x100000000 * v5 / 0x100000000 + v7));
	printf("v5: %d | v7:%p\n", v5, v7);
	printf("first arg:%p | %ld|%p | v6:%p|%ld\n", str2, len, &v5, &v6, (void*)&v6 - (void*)&str);
	printf("%p\n", argv[2]);
    if (*str != *(char *)(v5 + v7)) {
        // 0x40097e
        segf();
        // UNREACHABLE
    }
	printf ("B|%ld\n", f2(v3, len));
    char v8 = *(char *)(0x100000000 * f2(v3, len) / 0x100000000 + v7); // 0x4009a7
	printf("%d\n", v8);
    if (*(char *)(v4 + 1) != v8) {
        // 0x4009b0
        segf();
        // UNREACHABLE
    }
	printf ("C\n");
    char v9 = *(char *)(0x100000000 * f3(v3, len) / 0x100000000 + v7); // 0x4009d9
    if (*(char *)(v4 + 2) != v9) {
        // 0x4009e2
        segf();
        // UNREACHABLE
    }
    char v10 = *(char *)(0x100000000 * f4(v3, len) / 0x100000000 + v7); // 0x400a0b
    if (*(char *)(v4 + 3) != v10) {
        // 0x400a14
        segf();
        // UNREACHABLE
    }
	printf ("C\n");

    char v11 = *(char *)(0x100000000 * f5(v3, len) / 0x100000000 + v7); // 0x400a3d
    if (*(char *)(v4 + 4) != v11) {
        // 0x400a46
        segf();
        // UNREACHABLE
    }
    char v12 = *(char *)(0x100000000 * f6((int64_t)*str2 & 0xffffffff) / 0x100000000 + v7); // 0x400a6f
    if (*(char *)(v4 + 5) != v12) {
        // 0x400a78
        segf();
        // UNREACHABLE
    }
    // 0x400a7d
    puts("Congrats!");
    int64_t result = 1; // 0x400a99
    // 0x400aa0
    return result;
}
// --------------- Dynamically Linked Functions ---------------
// void __stack_chk_fail(void);
// int puts(const char * s);
// int rand(void);
// void srand(unsigned int seed);
// size_t strlen(const char * s);
// --------------------- Meta-Information ---------------------
// Detected compiler/packer: gcc (5.4.0)
// Detected functions: 8
