//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <openssl/md2.h>
// ------------------- Function Prototypes --------------------
int64_t function_4006d0(int64_t * a1);
int64_t function_4006e0(int64_t * a1, int64_t a2, int64_t a3);
int64_t function_400740(int64_t * a1, int64_t * a2, int64_t * a3);
// --------------------- Global Variables ---------------------
int32_t g1;
// ------------------------ Functions -------------------------
// Address range: 0x4006d0 - 0x4006d6
int64_t function_4006d0(int64_t * a1) {
    // 0x4006d0
    return MD5_Init(a1);
}
// Address range: 0x4006e0 - 0x4006e6
int64_t function_4006e0(int64_t * a1, int64_t a2, int64_t a3) {
    // 0x4006e0
    return MD5_Update(a1, a2, a3);
}
// Address range: 0x400740 - 0x400746
int64_t function_400740(int64_t * a1, int64_t * a2, int64_t * a3) {
    // 0x400740
    return MD5_Final(a1, a2);
}
// Address range: 0x400876 - 0x400a51
int main(int argc, char ** argv) {
    int64_t v1; // 0x400895
    int64_t str4 = 0; // bp-56, 0x4008a4
    int64_t * v2; // 0x400876
    int64_t v3; // 0x400876
    if ((int32_t)argc == 1) {
        // 0x40092b
        int64_t v4; // 0x400876
        int64_t * v5 = (int64_t *)v4; // 0x400932
        int64_t str = *v5; // 0x400932
        if (str != 0) {
            // 0x4008f0
            v2 = v5;
            if (strncmp((char *)str, "jennieandjayloveasm=", 20) != 0) {
                int64_t v6; // 0x400876
                int64_t v7 = v6 + 8;
                int64_t * v8 = (int64_t *)v7; // 0x400932
                int64_t str2 = *v8; // 0x400932
                while (str2 != 0) {
                    // 0x4008f0
                    v2 = v8;
                    if (strncmp((char *)str2, "jennieandjayloveasm=", 20) == 0) {
                        goto lab_0x40093a;
                    }
                    v7 += 8;
                    v8 = (int64_t *)v7;
                    str2 = *v8;
                }
                // 0x400944
                puts("Access Denied");
                v3 = 1;
                goto lab_0x400a3b;
            } else {
                goto lab_0x40093a;
            }
        } else {
            // 0x400944
            puts("Access Denied");
            v3 = 1;
            goto lab_0x400a3b;
        }
    } else {
        // 0x4008dc
        puts("Access Denied");
        v3 = 1;
        goto lab_0x400a3b;
    }
  lab_0x40093a:;
    int64_t v9 = *v2; // 0x400917
    if (v9 != 0) {
        int64_t str3 = v9 + 20; // 0x400958
        int64_t v10; // bp-168, 0x400876
        function_4006d0(&v10);
        int32_t len = strlen((char *)str3); // 0x400979
        function_4006e0(&v10, str3, (int64_t)len);
        int64_t v11; // bp-72, 0x400876
        function_400740(&v11, &v10, &v10);
        int64_t v12 = &str4; // 0x4009d4
        for (int64_t i = 0; i < 16; i++) {
            // 0x4009bc
            int64_t v13; // bp-8, 0x400876
            unsigned char v14 = *(char *)((int64_t)&v13 - 64 + i); // 0x4009c4
            sprintf((char *)(2 * i + v12), "%02x", (int32_t)v14);
        }
        // 0x400a02
        if (strcmp("e99a18c428cb38d5f260853678922e03", (char *)&str4) != 0) {
            // 0x400a2c
            puts("Access Denied");
            v3 = 1;
        } else {
            // 0x400a1b
            puts("Access Granted");
            v3 = 0;
        }
        goto lab_0x400a3b;
    } else {
        // 0x400944
        puts("Access Denied");
        v3 = 1;
        goto lab_0x400a3b;
    }
  lab_0x400a3b:;
    int64_t result = v3; // 0x400a48
    // 0x400a4f
    return result;
}
// --------------- Dynamically Linked Functions ---------------
// void __stack_chk_fail(void);
// int64_t MD5_Final(void);
// int64_t MD5_Init(void);
// int64_t MD5_Update(void);
// int puts(const char * s);
// int sprintf(char * restrict s, const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);
// size_t strlen(const char * s);
// int strncmp(const char * s1, const char * s2, size_t n);
// --------------------- Meta-Information ---------------------
// Detected compiler/packer: gcc (5.4.0)
// Detected functions: 4
